apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  labels:
    app: ghost
    tier: blog
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: ghost
      tier: blog
  template:
    metadata:
      labels:
        app: ghost
        tier: blog
    spec:
      containers:
      - name: ghost
        image: ghost:4.22.0-alpine
        # Ghost health check endpoint
        # https://github.com/TryGhost/Ghost/issues/11181#issuecomment-700619087
        # curl -s 'http://localhost:8083/ghost/api/v3/admin/site/
        # There is NO /health @ the moment
        # workaround for Kubernetes --> https://github.com/TryGhost/Ghost/issues/11181#issuecomment-829906250
        livenessProbe:
          httpGet:
            path: /ghost/api/v4/admin/site/
            port: ghost-port
            httpHeaders:
            - name: X-Forwarded-Proto
              value: https
            - name: Host
              value: new-ghost.devops-caffe.com
        readinessProbe:
          httpGet:
            path: /ghost/api/v4/admin/site/
            port: ghost-port
            httpHeaders:
            - name: X-Forwarded-Proto
              value: https
            - name: Host
              value: new-ghost.devops-caffe.com
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 2368
            name: ghost-port
        volumeMounts:
            - name: ghost-blog-content
              mountPath: /var/lib/ghost/content
        env:
        - name: NODE_ENV
          value: "production"

        - name: database__client
          value: mysql
        - name: database__connection__host
          value: ghost-mysql
        - name: database__connection__password
          value: password22
        - name: database__connection__database
          value: ghostblog
        - name: database__connection__user
          value: ghost
        # - name: GHOST_CONTENT
        #   value: /var/lib/ghost
        # - name: DB_USER
        #   value: ghost
        # - name: DB_PASSWORD
        #   value: password
        # - name: DB_NAME
        #   value: ghostblog
        - name: url
          value: http://new-ghost.devops-caffe.com
      volumes:
        - name: ghost-blog-content
          persistentVolumeClaim:
            claimName: ghost-blog-content
---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ghost
  namespace: ghost
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ghost
  minReplicas: 2
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ghost-blog-content
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: nfs-client

---

apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  selector:
    app: ghost
    tier: blog
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 2368 # Pod port

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ghost-blog
  namespace: ghost
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  rules:
  - host: new-ghost.devops-caffe.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ghost
          servicePort: 80
